pipeline {
    agent any
    stages {
         stage('Build') {
            steps {
               echo "build successful"
              bat "mvn clean"
            }
        }
        stage('Deploy') {
            steps {
               echo "Test successful"
              bat "mvn compile"
            }
        }
       
        stage('Test') {
            steps {
                echo "Test successful"
              bat "mvn test"
            }
        }
        
    }
}
